quarkus.index-dependency.rimfrost-framework-regel.group-id=se.fk.rimfrost.framework.regel
quarkus.index-dependency.rimfrost-framework-regel.artifact-id=rimfrost-framework-regel

mp.messaging.outgoing.regel-responses.topic=framework-regel-maskinell