# Dependencies to other framework components

quarkus.index-dependency.rimfrost-framework-regel.group-id=se.fk.rimfrost.framework.regel
quarkus.index-dependency.rimfrost-framework-regel.artifact-id=rimfrost-framework-regel
quarkus.index-dependency.rimfrost-referensdata-erbjudande.group-id=se.fk.rimfrost.referensdata
quarkus.index-dependency.rimfrost-referensdata-erbjudande.artifact-id=rimfrost-referensdata-erbjudande

rimfrost.framework.regel.maskinell.retry.intervals=15,30,60,120,240,480,960,1920,3840,7680,15360,30720