# Dependencies to other framework components

quarkus.index-dependency.rimfrost-framework-regel.group-id=se.fk.rimfrost.framework.regel
quarkus.index-dependency.rimfrost-framework-regel.artifact-id=rimfrost-framework-regel
quarkus.index-dependency.rimfrost-framework-uppgift-status-provider.group-id=se.fk.rimfrost.framework.uppgiftstatusprovider
quarkus.index-dependency.rimfrost-framework-uppgift-status-provider.artifact-id=rimfrost-framework-uppgift-status-provider